# Base image
FROM condaforge/miniforge3:25.3.1-0

# Set working directory
WORKDIR /usr/src/app

# System compilers for C++ extensions
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the environment file
COPY docker/pybase.yaml ./pybase.yaml

# Create the Python conda environment
RUN conda env create -f pybase.yaml --quiet --yes

# Expose path
ENV PATH=/opt/conda/envs/pybase/bin:$PATH

# Clean up conda cache to reduce image size
RUN conda clean -afy
