channel_alias_map: # channel to marker name. Important for reading FCS files into R (flowCore)
  "FSC-A": "FSC-A"
  "FSC-H": "FSC-H"
  "FSC-W": "FSC-W"
  "SSC-A": "SSC-A"
  "SSC-H": "SSC-H"
  "SSC-W": "SSC-W"
  "BUV395": "CD4"
  "BUV496": "CD3"
  "[AF color 1]": "[AF color 1]"
  "[AF color 2]": "[AF color 2]"
  "BUV661": "CD27"
  "BUV737": "CRTH2"
  "BV480": "CD45RA"
  "BV605": "CD127"
  "BV650": "CCR6"
  "BV785": "PD1"
  "BB700": "CD161"
  "[RB780]": "CTLA4"
  "PE-A": "CD8"
  "PE-CF594-A": "CD154"
  "PE-Cy5-A": "CD137"
  "PE-Cy7-A": "CD25"
  "APC": "ST2"
  "FVS780": "FVS780"
  "TIME": "Time"
