markers_to_transform: # list of markers to transform (must correspond to alias in channel_alias_map)
  - "CD4"
  - "CD3"
  - "CD27"
  - "CRTH2"
  - "CD45RA"
  - "CD127"
  - "CCR6"
  - "PD1"
  - "CD161"
  - "CTLA4"
  - "CD8"
  - "CD154"
  - "CD137"
  - "CD25"
  - "ST2"

downsample_size: # number of cells to sample per fcs file for cofactor prediction
# the smaller the number, the fast the calculations are, but may be less precise
  1000
